name: mfa
description: Mfa Amplify Sample
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  amplify_flutter: ^1.5.0
  amplify_auth_cognito: ^1.5.0
  amplify_core:
  amplify_auth_cognito_dart:
  asp: ^1.3.0
  auto_injector: ^2.0.2
  result_dart: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3

dependency_overrides:
  amplify_core:
    git:
      url: git@github.com:dtodt/amplify-flutter.git
      path: packages/amplify_core
      ref: auth/bug-forget-local-device
  amplify_auth_cognito_dart:
    git:
      url: git@github.com:dtodt/amplify-flutter.git
      path: packages/auth/amplify_auth_cognito_dart
      ref: auth/bug-forget-local-device

flutter:
  uses-material-design: true
